### ISSUE TITLE
Type error: Exception::__construct(): Argument #2 ($code) must be of type int, string given

### ISSUE THREAD

**Issue by mvorisek** [instaclick/php-webdriver#108]
Stack trace:
```
       Behat\Testwork\Call\Exception\FatalThrowableError: Type error: Exception::__construct(): Argument #2 ($code) must be of type int, string given in vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:144
      Stack trace:
      #0 vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php(144): Exception->__construct()
      #1 vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(172): WebDriver\Exception::factory()
      #2 vendor/instaclick/php-webdriver/lib/WebDriver/WebDriver.php(70): WebDriver\AbstractWebDriver->curl()
      #3 vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(301): WebDriver\WebDriver->session()
      #4 vendor/behat/mink/src/Session.php(70): Behat\Mink\Driver\Selenium2Driver->start()
```

full CI output https://github.com/atk4/ui/runs/3884923387?check_suite_focus=true incl. installed verisons

**Comment by robocoder** [comment]
@mvorisek I backported some fixes from the master branch to 1.x, and tagged it as 1.4.10. Let me know how that goes.

**Comment by robocoder** [comment]
I'll add to my todo list.

What version of Selenium did you downgrade to?

**Comment by mvorisek** [comment]
https://github.com/SeleniumHQ/docker-selenium/releases

I am using the latest 3.x (3.141.59-20210929), the new 4.x is not compatible. I will close this issue as it was for the php type error.
